//get Forgot password by email
export const GET_FORGOT_PASSWORD_BY_EMAIL = 'GET_FORGOT_PASSWORD_BY_EMAIL';
export const GET_FORGOT_PASSWORD_BY_EMAIL_SUCCESS =
  'GET_FORGOT_PASSWORD_BY_EMAIL_SUCCESS';
export const GET_FORGOT_PASSWORD_BY_EMAIL_ERROR =
  'GET_FORGOT_PASSWORD_BY_EMAIL_ERROR';
export const LOGOUT = 'LOGOUT';

//verify user by code number
export const VERIFY_USER_BY_CODE_NUMBER = 'VERIFY_USER_BY_CODE_NUMBER';
export const VERIFY_USER_BY_CODE_NUMBER_SUCCESS =
  'VERIFY_USER_BY_CODE_NUMBER_SUCCESS';
export const VERIFY_USER_BY_CODE_NUMBER_ERROR =
  'VERIFY_USER_BY_CODE_NUMBER_ERROR';

//reset password
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const RESET_PASSWORD_NULL = 'RESET_PASSWORD_NULL';
