export const routes = {
  SIGNUPSCREENS: 'SIGNUPSCREENS',
  LOGINSCREENS: 'LOGINSCREENS',
  HOMESCREENS: 'HOMESCREENS',
  POSTSCREENS: 'POSTSCREENS',
  NOTIFICATIONSCREENS: 'NOTIFICATIONSCREENS',
  PROFILESCREENS: 'PROFILESCREENS',
  INFORMATIONSCREEN: 'INFORMATIONSCREEN',
  CHATSCREENS: 'CHATSCREENS',
  BOTTOMTABBAR: 'BOTTOMTABBAR',
  DETAILSCREENS: 'DETAILSCREENS',
  MYBILLSCREENS: 'MYBILLSCREENS',
  OPTIONSCREENS: 'OPTIONSCREENS',
};
