export const routes = {
  SIGNUPSCREENS: 'SIGNUPSCREENS',
  LOGINSCREENS: 'LOGINSCREENS',
  HOMESCREENS: 'HOMESCREENS',
  CATEGORYSCREENS: 'CATEGORYSCREENS',
  NOTIFICATIONSCREENS: 'NOTIFICATIONSCREENS',
  PROFILESCREENS: 'PROFILESCREENS',
  CHATSCREENS: 'CHATSCREENS',
  BOTTOMTABBAR: 'BOTTOMTABBAR',
};
