export const routes = {
  SIGNUPSCREENS: 'SIGNUPSCREENS',
  LOGINSCREENS: 'LOGINSCREENS',
  HOMESCREENS: 'HOMESCREENS',
  POSTSCREENS: 'POSTSCREENS',
  NOTIFICATIONSCREENS: 'NOTIFICATIONSCREENS',
  PROFILESCREENS: 'PROFILESCREENS',
  CHATSCREENS: 'CHATSCREENS',
  BOTTOMTABBAR: 'BOTTOMTABBAR',
  DETAILSCREENS: 'DETAILSCREENS',
};
